@echo off
ren gstock_00_modules.png         portfolio-details-work1-01.png
ren gstock_01_ar.png                portfolio-details-work1-02.png
ren gstock_01_fr.png                portfolio-details-work1-03.png
ren gstock_02_database.png                portfolio-details-work1-04.png
ren gstock_03.png                portfolio-details-work1-05.png
ren gstock_03_paginator.png                portfolio-details-work1-06.png
ren gstock_04.png                portfolio-details-work1-07.png
ren gstock_05.png                portfolio-details-work1-08.png
ren gstock_06.png                portfolio-details-work1-09.png
ren gstock_07.png                portfolio-details-work1-10.png
ren gstock_08.png                portfolio-details-work1-11.png
ren gstock_09.png                portfolio-details-work1-12.png
ren gstock_10.png                portfolio-details-work1-13.png
ren gstock_11.png                portfolio-details-work1-14.png
ren gstock_12.png                portfolio-details-work1-15.png
ren gstock_13_CodeExample.png                portfolio-details-work1-16.png
ren gstock_14_CodeExample.png                portfolio-details-work1-17.png
ren gstock_15_CodeExample.png                portfolio-details-work1-18.png
ren gstock_16_CodeExample.png                portfolio-details-work1-19.png
ren gstock_17_CodeExample.png                portfolio-details-work1-20.png
ren gstock_18_CodeExample.png                portfolio-details-work1-21.png
ren gstock_19-1_CodeExample.png                portfolio-details-work1-22.png
ren gstock_19-2_CodeExample.png                portfolio-details-work1-23.png
ren gstock_19-3_CodeExample.png                portfolio-details-work1-24.png
ren gstock_20_CodeExample.png                portfolio-details-work1-25.png
ren gstock_21_CodeExample.png                portfolio-details-work1-26.png
ren gstock_22-1_CodeExample.png                portfolio-details-work1-27.png
ren gstock_22-2_CodeExample.png                portfolio-details-work1-28.png
